### PR TITLE
Removing dead project

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @acgeospatial 

just removing a dead project.

Cheers!

### CODE REVIEW

**Comment by acgeospatial** [comment]
ah good spot, looks like its moved to here
https://github.com/remotesensinginfo/rsgislib

**Comment by acgeospatial** [comment]
I've made the change to https://github.com/remotesensinginfo/rsgislib so I am going to merge the requestm however I'll add you to contributors thanks very much!

**Comment by spekulatius** [comment]
Ah okay. We just worked on it at the same time - I've just updated the PR on my end... Timing :)

**Comment by acgeospatial** [comment]
sorry! I really appreciate the contribution though - I've added you to the list

**Comment by spekulatius** [comment]
No worries. We just been both too fast :D

**Pull request closed without merging**
