### PR TITLE
Added simrdwn and torchgeo to readme

### PR DESCRIPTION
**Pull request by danhirstos**
Added 2 packages
simrdwn is a object detector from cosmiq works
torchgeo is a package built on pytorch that adds some geospatial datasets and models

### CODE REVIEW

**Comment by acgeospatial** [comment]
thankyou - added. I'll add you to contributors

**Comment by danhirstos** [comment]
I have contributed before, so no need! Thanks a lot

**Comment by koyo-nic** [comment]
Awesome was just came by torchgeo on the pytorch ecosystem page yesterday. I was doing a comparison of available remote sensing models in torch hub vs tensorflowhub. This should really be a game change

**Comment by acgeospatial** [comment]
@danhirstos did you mean https://github.com/microsoft/torchgeo for torchgeo - your link points at pytorch. Just checking :)

**Comment by danhirstos** [comment]
> @danhirstos did you mean https://github.com/microsoft/torchgeo for torchgeo - your link points at pytorch. Just checking :)

Yes, that is exactly what I meant. I'll amend and resubmit the pull request

**Pull request merged**
